This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./Main.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Main.acn....done (95 entries accepted, 0 rejected).
Sorting entries....done (651 comparisons).
Generating output file Main.acr....done (75 lines written, 0 warnings).
Output written in Main.acr.
Transcript written in Main.alg.
